import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './features.css';
import './kindred-theme.css';
import './software-ui.css';

const money = n => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(n || 0));
const localDate = date => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const today = () => localDate(new Date());
const addDays = days => { const d = new Date(); d.setDate(d.getDate() + days); return localDate(d); };
const menuItems = ['Dashboard','Clients','Estimates','Invoices','Items','Subscriptions','Payments','Expenses','Tasks','Reports','Settings'];
const MenuIcon=({name})=>{const paths={Dashboard:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,Invoices:<><path d="M6 2h9l5 5v15H6z"/><path d="M14 2v6h6M9 13h8M9 17h6"/></>,Clients:<><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 1 3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,Estimates:<><rect x="5" y="4" width="14" height="18" rx="2"/><path d="M9 2h6v4H9zM9 11h6M9 15h6M9 19h4"/></>,Payments:<><rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20M6 15h4"/></>,Reports:<><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/><path d="m4 7 6-5 6 7 5-4"/></>,Settings:<><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V21h-4v-.08A1.7 1.7 0 0 0 9 19.37a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.63 15 1.7 1.7 0 0 0 3.08 14H3v-4h.08A1.7 1.7 0 0 0 4.63 9a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.63 1.7 1.7 0 0 0 10 3.08V3h4v.08A1.7 1.7 0 0 0 15 4.63a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.37 9 1.7 1.7 0 0 0 20.92 10H21v4h-.08A1.7 1.7 0 0 0 19.4 15z"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">{paths[name]}</svg>};
const apiJson=async(input,options)=>{const response=await fetch(input,{...options,headers:{accept:'application/json',...(options?.headers||{})}});const contentType=response.headers.get('content-type')||'';if(!contentType.includes('application/json')){throw new Error(response.redirected?'Your Zero Trust session needs to be refreshed. Sign in again, then retry.':'The invoice API is unavailable. The page server responded instead; retry after the API starts.')}const result=await response.json();if(!response.ok)throw new Error(result.error||`Request failed (${response.status})`);return result};

function App() {
  const [data,setData]=useState(null), [page,setPage]=useState('Dashboard'), [modal,setModal]=useState(null), [invoiceScreen,setInvoiceScreen]=useState(null), [clientScreen,setClientScreen]=useState(null);
  const [collapsed,setCollapsed]=useState(()=>localStorage.getItem('nav-collapsed')==='true');
  const [theme,setTheme]=useState(()=>localStorage.getItem('theme')||'light');
  const load=()=>apiJson('/api/workspace').then(setData);
  useEffect(()=>{let stopped=false,timer;const connect=remaining=>load().catch(error=>{if(stopped)return;if(remaining>0)timer=setTimeout(()=>connect(remaining-1),1000);else setData({error:error.message})});connect(4);return()=>{stopped=true;clearTimeout(timer)}},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('theme',theme)},[theme]);
  const toggleNav=()=>setCollapsed(v=>{localStorage.setItem('nav-collapsed',String(!v));return !v});
  const createForPage=()=>setModal(page==='Clients'?'client':page==='Estimates'?'estimate':page==='Items'?'item':page==='Subscriptions'?'subscription':page==='Payments'?'payment':page==='Expenses'?'expense':page==='Tasks'?'task':'invoice');
  if(!data)return <div className="loading"><span>Kindred</span><p>Preparing your workspace…</p></div>;
  if(data.error)return <div className="auth-error"><p>Protected workspace</p><h1>We could not open your workspace.</h1><span>{data.error}</span><button className="retry" onClick={()=>{setData(null);load().catch(e=>setData({error:e.message}))}}>Retry connection</button></div>;
  return <div className={`shell ${collapsed?'collapsed':''}`}>
    <aside><div className="brand"><div className="mark">ki</div><div className="brand-copy"><strong>Kindred</strong><span>Invoice care</span></div><button className="collapse" onClick={toggleNav} aria-label={collapsed?'Expand menu':'Collapse menu'} title={collapsed?'Expand menu':'Collapse menu'}>{collapsed?'›':'‹'}</button></div>
      <nav>{menuItems.map(item=><button key={item} title={item} aria-label={item} className={page===item?'active':''} onClick={()=>setPage(item)}><i><MenuIcon name={item}/></i><span>{item}</span></button>)}</nav>
      <div className="aside-note"><small>Careful systems</small><p>Your financial work, held clearly and securely.</p><span>Protected by Zero Trust</span></div>
      <div className="user"><div>{data.user.email[0].toUpperCase()}</div><span><strong>{data.user.name}</strong><small>{data.user.email}</small></span></div>
    </aside>
    <main className={`page-${page.toLowerCase()}`}><header><div><small>Kindred Invoice</small><h1>{page}</h1></div><div className="header-actions">{!['Dashboard','Invoices','Items','Subscriptions','Payments','Expenses','Tasks','Reports','Settings'].includes(page)&&<button className="primary" onClick={createForPage}>＋ New {page.slice(0,-1).toLowerCase()}</button>}</div></header>
      {page==='Dashboard'?<Dashboard data={data} go={setPage} openInvoice={invoice=>setInvoiceScreen({mode:'preview',invoice})}/>:page==='Clients'?<Clients data={data} open={setClientScreen}/>:page==='Invoices'?<Invoices data={data} create={()=>setModal('invoice')} open={invoice=>setInvoiceScreen({mode:'preview',invoice})}/>:page==='Estimates'?<Estimates data={data} reload={load}/>:page==='Items'?<Items data={data} create={()=>setModal('item')}/>:page==='Subscriptions'?<Subscriptions data={data} create={()=>setModal('subscription')}/>:page==='Payments'?<Payments data={data} create={()=>setModal('payment')} openInvoice={invoice=>setInvoiceScreen({mode:'preview',invoice})}/>:page==='Expenses'?<Expenses data={data} create={()=>setModal('expense')}/>:page==='Tasks'?<Tasks data={data} create={()=>setModal('task')}/>:page==='Reports'?<Reports data={data}/>:<Settings theme={theme} setTheme={setTheme} data={data} reload={load}/>} </main>
    {modal&&modal!=='invoice'&&<Modal config={typeof modal==='string'?{type:modal}:modal} data={data} close={()=>setModal(null)} saved={()=>{setModal(null);load()}}/>}
    {(invoiceScreen||modal==='invoice')&&<InvoiceScreen mode={invoiceScreen?.mode||'create'} invoice={invoiceScreen?.invoice} data={data} refresh={load} close={()=>{setInvoiceScreen(null);setModal(null)}} reload={async()=>{await load();setInvoiceScreen(null);setModal(null)}} recordPayment={invoiceId=>setModal({type:'payment',invoiceId})}/>}
    {clientScreen&&<ClientScreen client={clientScreen} data={data} close={()=>setClientScreen(null)} openInvoice={invoice=>setInvoiceScreen({mode:'preview',invoice})}/>}
  </div>;
}

const Empty=({title,text,action})=><div className="empty"><span>◇</span><small>Ready when you are</small><h2>{title}</h2><p>{text}</p>{action}</div>;
function Dashboard({data,go,openInvoice}) {
  const total=data.invoices.reduce((s,i)=>s+i.amount,0), collected=data.payments.reduce((s,p)=>s+p.amount,0), due=data.invoices.reduce((s,i)=>s+i.balance,0);
  const draftInvoices=data.invoices.filter(i=>i.status==='draft'), sentInvoices=data.invoices.filter(i=>i.status==='sent'), overdueInvoices=data.invoices.filter(i=>i.status==='overdue');
  const draftEstimates=data.estimates.filter(e=>e.status==='draft'), activeEstimates=data.estimates.filter(e=>['sent','approved'].includes(e.status)), convertedEstimates=data.estimates.filter(e=>e.status==='converted');
  return <>{!data.clients.length&&<div className="welcome"><small>Start here</small><h2>Build a clear financial rhythm.</h2><p>Add your first client, then create an estimate or invoice. Nothing here is sample data—this workspace is entirely yours.</p><button className="primary" onClick={()=>go('Clients')}>Add your first client</button></div>}
    <section className="dashboard-heading"><div><h2>Financial dashboard</h2><p>Your invoice, quote, and payment activity at a glance.</p></div><span>{new Date().toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</span></section>
    <section className="panel kpi-panel"><div className="panel-head"><div><small>Workspace totals</small><h3>KPI cards</h3></div><button className="quiet" onClick={()=>go('Reports')}>View reports</button></div><div className="stats dashboard-stats"><Stat label="Draft invoices" value={money(draftInvoices.reduce((s,i)=>s+i.amount,0))} note={`${draftInvoices.length} invoices`} tone="slate"/><Stat label="Sent invoices" value={money(sentInvoices.reduce((s,i)=>s+i.amount,0))} note={`${sentInvoices.length} invoices`} tone="gold"/><Stat label="Overdue invoices" value={money(overdueInvoices.reduce((s,i)=>s+i.balance,0))} note={`${overdueInvoices.length} overdue`} tone="red"/><Stat label="Payments collected" value={money(collected)} note={`${data.payments.length} payments`} tone="green"/><Stat label="Draft quotes" value={money(draftEstimates.reduce((s,e)=>s+e.amount,0))} note={`${draftEstimates.length} estimates`} tone="pink"/><Stat label="Sent / approved quotes" value={money(activeEstimates.reduce((s,e)=>s+e.amount,0))} note={`${activeEstimates.length} active`} tone="cyan"/><Stat label="Converted quotes" value={money(convertedEstimates.reduce((s,e)=>s+e.amount,0))} note={`${convertedEstimates.length} converted`} tone="coral"/><Stat label="Payments due" value={money(due)} note={`${data.invoices.filter(i=>i.balance>0).length} open invoices`} tone="olive"/></div></section>
    <section className="panel recent"><div className="panel-head"><div><small>Recent work</small><h3>Latest invoices</h3></div><button className="text-btn" onClick={()=>go('Invoices')}>View all →</button></div>{data.invoices.length?<InvoiceTable data={data} open={openInvoice}/>:<p className="nothing">No invoices yet.</p>}</section></>;
}
const Stat=({label,value,note,tone})=><div className={`stat ${tone}`}><small>{label}</small><strong>{value}</strong><span>{note}</span></div>;
const fieldsFor=(data,type)=>data.settings?.customFields?.filter(field=>field.appliesTo===type)||[];
const CustomValues=({data,type,record})=>{const values=fieldsFor(data,type).filter(field=>record.customFields?.[field.id]);return values.length?<div className="custom-values">{values.map(field=><span key={field.id}><small>{field.label}</small>{record.customFields[field.id]}</span>)}</div>:null};
function InvoiceTable({data,open}) { return <div className="table"><div className="tr th invoice-row"><span>Invoice</span><span>Client</span><span>Due</span><span>Status</span><span>Balance</span><span></span></div>{data.invoices.map(i=><button type="button" className="tr invoice-row invoice-link" key={i.id} onClick={()=>open?.(i)}><span><strong>{i.id}</strong><small>{i.description}</small><CustomValues data={data} type="invoice" record={i}/></span><span>{data.clients.find(c=>c.id===i.clientId)?.name}</span><span>{i.due}</span><span><em className={`status ${i.status}`}>{i.status}</em></span><span><strong>{money(i.balance)}</strong><small>{money(i.paid)} paid</small></span><span className="view-invoice">Open invoice →</span></button>)}</div> }
function Invoices({data,open,create}) {
  const [search,setSearch]=useState(''),[clientId,setClientId]=useState('all'),[status,setStatus]=useState('all'),[date,setDate]=useState('');
  const visible=data.invoices.filter(invoice=>{const client=data.clients.find(item=>item.id===invoice.clientId),needle=search.trim().toLowerCase();return (!needle||invoice.id.toLowerCase().includes(needle)||invoice.description.toLowerCase().includes(needle)||client?.name.toLowerCase().includes(needle))&&(clientId==='all'||invoice.clientId===clientId)&&(status==='all'||invoice.status===status)&&(!date||invoice.issued===date||invoice.due===date)});
  return <section className="invoice-index"><div className="index-heading"><div><span className="index-icon">▤</span><h2>Invoices</h2></div><nav><span className="home-crumb">Home</span><span>/</span><strong>Invoices</strong></nav></div><section className="panel page-panel invoice-index-panel"><div className="invoice-toolbar"><div className="invoice-search"><span>⌕</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search invoices" aria-label="Search invoices"/></div><div className="invoice-filters"><input type="date" value={date} onChange={event=>setDate(event.target.value)} aria-label="Filter by date"/><select value={clientId} onChange={event=>setClientId(event.target.value)} aria-label="Filter by client"><option value="all">Select client</option>{data.clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select><select value={status} onChange={event=>setStatus(event.target.value)} aria-label="Filter by status"><option value="all">All statuses</option><option value="draft">Draft</option><option value="sent">Sent</option><option value="paid">Paid</option><option value="overdue">Overdue</option><option value="void">Void</option></select><button className="primary" onClick={create}>＋ New</button></div></div>{visible.length?<div className="software-invoice-table"><div className="software-invoice-row software-invoice-head"><span>Invoice</span><span>Date</span><span>Due</span><span>Client</span><span>Status</span><span>Summary</span><span>Total</span></div>{visible.map(invoice=>{const client=data.clients.find(item=>item.id===invoice.clientId);return <button type="button" className="software-invoice-row" key={invoice.id} onClick={()=>open(invoice)}><strong>{invoice.id}</strong><span>{invoice.issued}</span><span>{invoice.due}</span><span className="client-link">{client?.name}</span><span><em className={`status ${invoice.status}`}>{invoice.status}</em></span><span className="invoice-summary-text">{invoice.description}</span><strong>{money(invoice.amount)}</strong></button>})}</div>:<div className="invoice-index-empty"><strong>No matching invoices</strong><span>Adjust the search or filters to see more records.</span></div>}</section></section>;
}
function Items({data,create}) {
  const items=data.items||[],[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[category,setCategory]=useState('all');
  const categories=[...new Set(items.map(item=>item.category).filter(Boolean))].sort(),needle=search.trim().toLowerCase();
  const visible=items.filter(item=>(!needle||[item.name,item.company,item.category,item.description].some(value=>String(value).toLowerCase().includes(needle)))&&(status==='all'||item.status===status)&&(category==='all'||item.category===category));
  return <section className="items-index"><div className="index-heading"><div><span className="index-icon">▣</span><h2>Items</h2></div><nav><span className="home-crumb">Home</span><span>/</span><strong>Items</strong></nav></div><section className="panel page-panel items-index-panel"><div className="invoice-toolbar"><div className="invoice-search"><span>⌕</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search items" aria-label="Search items"/></div><div className="invoice-filters"><select value={status} onChange={event=>setStatus(event.target.value)} aria-label="Filter by status"><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select><select value={category} onChange={event=>setCategory(event.target.value)} aria-label="Filter by category"><option value="all">All categories</option>{categories.map(value=><option key={value} value={value}>{value}</option>)}</select><button className="primary" onClick={create}>＋ New</button></div></div><div className="software-items-table"><div className="software-item-row software-invoice-head"><span>Item</span><span>Company</span><span>Category</span><span>Description</span><span>In stock</span><span>Price</span><span>Tax 1</span><span>Tax 2</span><span>Status</span></div>{visible.map(item=><div className="software-item-row" key={item.id}><strong>{item.name}</strong><span>{item.company||'—'}</span><span>{item.category||'—'}</span><span className="invoice-summary-text">{item.description||'—'}</span><span>{item.stock}</span><strong>{money(item.price)}</strong><span>{item.tax1}%</span><span>{item.tax2}%</span><em className={`status ${item.status}`}>{item.status}</em></div>)}</div>{!visible.length&&<div className="invoice-index-empty"><strong>{items.length?'No matching items':'No items available'}</strong><span>{items.length?'Adjust the search or filters.':'Create your first reusable product or service item.'}</span></div>}</section></section>;
}
function Subscriptions({data,create}) {
  const subscriptions=data.subscriptions||[];
  const [search,setSearch]=useState(''),[status,setStatus]=useState('all'),[clientId,setClientId]=useState('all'),[date,setDate]=useState('');
  const needle=search.trim().toLowerCase();
  const visible=subscriptions.filter(subscription=>{
    const client=data.clients.find(item=>item.id===subscription.clientId),matchesSearch=!needle||subscription.id.toLowerCase().includes(needle)||subscription.summary.toLowerCase().includes(needle)||String(client?.name||'').toLowerCase().includes(needle);
    return matchesSearch&&(status==='all'||subscription.status===status)&&(clientId==='all'||subscription.clientId===clientId)&&(!date||subscription.nextDate===date||subscription.stopDate===date);
  });
  const pageTotal=visible.reduce((sum,subscription)=>sum+subscription.amount,0);
  return <section className="subscriptions-index"><div className="index-heading"><div><span className="index-icon">⟳</span><h2>Subscriptions</h2></div><nav><span className="home-crumb">Home</span><span>/</span><strong>Subscriptions</strong></nav></div><section className="panel page-panel subscriptions-index-panel"><div className="invoice-toolbar"><div className="invoice-search"><span>⌕</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search subscriptions" aria-label="Search subscriptions"/></div><div className="invoice-filters"><input type="date" value={date} onChange={event=>setDate(event.target.value)} aria-label="Filter by date"/><select value={clientId} onChange={event=>setClientId(event.target.value)} aria-label="Filter by client"><option value="all">Select client</option>{data.clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select><select value={status} onChange={event=>setStatus(event.target.value)} aria-label="Filter by status"><option value="all">All statuses</option><option value="active">Active</option><option value="paused">Paused</option><option value="ended">Ended</option></select><button className="primary" onClick={create}>＋ New</button></div></div><div className="software-subscription-table"><div className="software-subscription-row software-invoice-head"><span>ID</span><span>Client</span><span>Summary</span><span>Next date</span><span>Stop date</span><span>Every</span><span>Status</span><span>Total</span></div>{visible.map(subscription=>{const client=data.clients.find(item=>item.id===subscription.clientId);return <div className="software-subscription-row" key={subscription.id}><strong>{subscription.id.replace('sub_','').slice(0,8)}</strong><span className="client-link">{client?.name}</span><span className="invoice-summary-text">{subscription.summary}</span><span>{subscription.nextDate}</span><span>{subscription.stopDate||'—'}</span><span>{subscription.intervalCount} {subscription.intervalUnit}</span><em className={`status ${subscription.status}`}>{subscription.status}</em><strong>{money(subscription.amount)}</strong></div>})}</div>{!visible.length&&<div className="invoice-index-empty"><strong>{subscriptions.length?'No matching subscriptions':'No subscriptions available'}</strong><span>{subscriptions.length?'Adjust the search or filters.':'Create the first recurring billing schedule.'}</span></div>}{visible.length>0&&<div className="subscription-total"><span>Page total</span><strong>{money(pageTotal)}</strong></div>}</section></section>;
}
function Clients({data,open}) { return data.clients.length?<section className="panel page-panel client-list"><div className="client-list-row client-list-head"><span>Client</span><span>Location</span><span>Invoices</span><span>Paid</span><span>Due</span><span></span></div>{data.clients.map(client=>{const invoices=data.invoices.filter(invoice=>invoice.clientId===client.id),invoiceIds=new Set(invoices.map(invoice=>invoice.id)),payments=data.payments.filter(payment=>invoiceIds.has(payment.invoiceId));return <button type="button" className="client-list-row" key={client.id} onClick={()=>open(client)}><span><b className="client-avatar">{client.name[0]}</b><strong>{client.name}</strong></span><span>{client.city}, {client.state} {client.zip}</span><span>{invoices.length}</span><span>{money(payments.reduce((sum,payment)=>sum+payment.amount,0))}</span><span>{money(invoices.reduce((sum,invoice)=>sum+invoice.balance,0))}</span><span>Open client →</span></button>})}</section>:<Empty title="No clients yet" text="Clients include their service location, optional hourly rate, invoices, estimates, payments made, and balance due."/>; }
function Estimates({data,reload}) { const convert=async id=>{const r=await fetch(`/api/estimates/${id}/convert`,{method:'POST'});if(r.ok)reload()};return data.estimates.length?<section className="panel page-panel"><div className="table"><div className="tr th estimate-row"><span>Estimate</span><span>Client</span><span>Quote</span><span>Valid until</span><span>Amount</span><span></span></div>{data.estimates.map(e=><div className="tr estimate-row" key={e.id}><span><strong>{e.id}</strong><small>{e.status}</small></span><span>{data.clients.find(c=>c.id===e.clientId)?.name}</span><span>{e.quote}<CustomValues data={data} type="estimate" record={e}/></span><span>{e.validUntil}</span><span><strong>{money(e.amount)}</strong></span><span>{e.status!=='converted'?<button className="mini" onClick={()=>convert(e.id)}>Convert to invoice</button>:<small>{e.invoiceId}</small>}</span></div>)}</div></section>:<Empty title="No estimates yet" text="Write a quote, set its value and validity date, then convert it to an invoice with one click."/>; }
function Payments({data,create,openInvoice}) {
  const [search,setSearch]=useState(''),[date,setDate]=useState(''),[clientId,setClientId]=useState('all'),[method,setMethod]=useState('all'),needle=search.trim().toLowerCase();
  const visible=data.payments.filter(payment=>{const invoice=data.invoices.find(item=>item.id===payment.invoiceId),client=data.clients.find(item=>item.id===invoice?.clientId);return (!needle||payment.id.toLowerCase().includes(needle)||payment.invoiceId.toLowerCase().includes(needle)||String(client?.name||'').toLowerCase().includes(needle))&&(!date||payment.date===date)&&(clientId==='all'||invoice?.clientId===clientId)&&(method==='all'||payment.method===method)});
  return <section className="payments-index"><div className="index-heading"><div><span className="index-icon">▰</span><h2>Payments Collected</h2></div><nav><span className="home-crumb">Home</span><span>/</span><strong>Payments</strong></nav></div><section className="panel page-panel payments-index-panel"><div className="invoice-toolbar"><div className="invoice-search"><span>⌕</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search payments" aria-label="Search payments"/></div><div className="invoice-filters"><input type="date" value={date} onChange={event=>setDate(event.target.value)} aria-label="Filter by date"/><select value={clientId} onChange={event=>setClientId(event.target.value)} aria-label="Filter by client"><option value="all">Select client</option>{data.clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select><select value={method} onChange={event=>setMethod(event.target.value)} aria-label="Filter by payment method"><option value="all">All payment methods</option><option value="cash">Cash</option><option value="check">Check</option><option value="credit_card">Credit card</option></select><button className="primary" onClick={create}>＋ New</button></div></div><div className="software-payment-table"><div className="software-payment-row software-invoice-head"><span>ID</span><span>Payment date</span><span>Client</span><span>Payment method</span><span>Payment</span><span>Balance</span><span>Invoice number</span></div>{visible.map(payment=>{const invoice=data.invoices.find(item=>item.id===payment.invoiceId),client=data.clients.find(item=>item.id===invoice?.clientId);return <div className="software-payment-row" key={payment.id}><strong>{payment.id}</strong><span>{payment.date}</span><span className="client-link">{client?.name}</span><span className="method">{payment.method.replace('_',' ')}</span><strong>{money(payment.amount)}</strong><span>{money(invoice?.balance)}</span><button type="button" onClick={()=>invoice&&openInvoice(invoice)}>{payment.invoiceId}</button></div>})}</div>{!visible.length&&<div className="invoice-index-empty"><strong>{data.payments.length?'No matching payments':'No payments collected'}</strong><span>{data.payments.length?'Adjust the search or filters.':'Record the first payment against an open invoice.'}</span></div>}</section></section>;
}
function Expenses({data,create}) {
  const expenses=data.expenses||[],[search,setSearch]=useState(''),[date,setDate]=useState(''),[status,setStatus]=useState('all'),[category,setCategory]=useState('all'),[vendor,setVendor]=useState('all'),[clientId,setClientId]=useState('all'),needle=search.trim().toLowerCase();
  const categories=[...new Set(expenses.map(expense=>expense.category).filter(Boolean))].sort(),vendors=[...new Set(expenses.map(expense=>expense.vendor).filter(Boolean))].sort();
  const visible=expenses.filter(expense=>{const client=data.clients.find(item=>item.id===expense.clientId);return (!needle||[expense.id,expense.vendor,expense.company,expense.category,expense.description,client?.name].some(value=>String(value||'').toLowerCase().includes(needle)))&&(!date||expense.date===date)&&(status==='all'||expense.status===status)&&(category==='all'||expense.category===category)&&(vendor==='all'||expense.vendor===vendor)&&(clientId==='all'||expense.clientId===clientId)});
  return <section className="expenses-index"><div className="index-heading"><div><span className="index-icon">▣</span><h2>Expenses</h2></div><nav><span className="home-crumb">Home</span><span>/</span><strong>Expenses</strong></nav></div><section className="panel page-panel expenses-index-panel"><div className="invoice-toolbar expense-toolbar"><div className="invoice-search"><span>⌕</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search expenses" aria-label="Search expenses"/></div><div className="invoice-filters"><input type="date" value={date} onChange={event=>setDate(event.target.value)} aria-label="Filter by date"/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All statuses</option><option value="unbilled">Unbilled</option><option value="billed">Billed</option><option value="reimbursed">Reimbursed</option></select><select value={category} onChange={event=>setCategory(event.target.value)}><option value="all">All categories</option>{categories.map(value=><option key={value} value={value}>{value}</option>)}</select><select value={vendor} onChange={event=>setVendor(event.target.value)}><option value="all">All vendors</option>{vendors.map(value=><option key={value} value={value}>{value}</option>)}</select><select value={clientId} onChange={event=>setClientId(event.target.value)}><option value="all">Select client</option>{data.clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select><button className="primary" onClick={create}>＋ New</button></div></div><div className="software-expense-table"><div className="software-expense-row software-invoice-head"><span>ID</span><span>Vendor</span><span>Client</span><span>Date</span><span>Company</span><span>Category</span><span>Description</span><span>Tax</span><span>Amount</span></div>{visible.map(expense=>{const client=data.clients.find(item=>item.id===expense.clientId);return <div className="software-expense-row" key={expense.id}><strong>{expense.id}</strong><span className="client-link">{expense.vendor}</span><span className="client-link">{client?.name||'—'}</span><span>{expense.date}</span><span>{expense.company||'—'}</span><span>{expense.category||'—'}</span><span className="invoice-summary-text">{expense.description}</span><span>{money(expense.tax)}</span><span className="expense-amount"><strong>{money(expense.amount)}</strong><em className={`status ${expense.status}`}>{expense.status}</em></span></div>})}</div>{!visible.length&&<div className="invoice-index-empty"><strong>{expenses.length?'No matching expenses':'No expenses available'}</strong><span>{expenses.length?'Adjust the search or filters.':'Create the first vendor expense.'}</span></div>}</section></section>;
}
function Tasks({data,create}) {
  const tasks=data.tasks||[],[search,setSearch]=useState(''),[scope,setScope]=useState('mine'),[status,setStatus]=useState('open'),[date,setDate]=useState(''),needle=search.trim().toLowerCase();
  const visible=tasks.filter(task=>{const client=data.clients.find(item=>item.id===task.clientId);return (!needle||[task.id,task.title,task.description,client?.name].some(value=>String(value||'').toLowerCase().includes(needle)))&&(scope==='all'||task.assigneeEmail===data.user.email)&&(status==='all'||task.status===status)&&(!date||task.dueDate===date)});
  return <section className="tasks-index"><div className="index-heading"><div><span className="index-icon">☷</span><h2>Tasks</h2></div><nav><span className="home-crumb">Home</span><span>/</span><strong>Tasks</strong></nav></div><section className="panel page-panel tasks-index-panel"><div className="invoice-toolbar"><div className="invoice-search"><span>⌕</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search tasks" aria-label="Search tasks"/></div><div className="invoice-filters"><select value={scope} onChange={event=>setScope(event.target.value)}><option value="mine">My tasks</option><option value="all">All tasks</option></select><select value={status} onChange={event=>setStatus(event.target.value)}><option value="open">Open</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="all">All statuses</option></select><input type="date" value={date} onChange={event=>setDate(event.target.value)} aria-label="Filter by due date"/><button className="primary" onClick={create}>＋ New</button></div></div><div className="software-task-table"><div className="software-task-row software-invoice-head"><span>ID</span><span>Title</span><span>Client</span><span>Description</span><span>Due date</span><span>Assignee</span><span>Completed</span><span>Status</span></div>{visible.map(task=>{const client=data.clients.find(item=>item.id===task.clientId);return <div className="software-task-row" key={task.id}><strong>{task.id}</strong><span className="task-title">{task.title}</span><span className="client-link">{client?.name||'—'}</span><span className="invoice-summary-text">{task.description||'—'}</span><span>{task.dueDate}</span><span>{task.assigneeEmail===data.user.email?'Me':task.assigneeEmail}</span><span>{task.completedAt?task.completedAt.slice(0,10):'—'}</span><em className={`status ${task.status}`}>{task.status.replace('_',' ')}</em></div>})}</div>{!visible.length&&<div className="invoice-index-empty"><strong>{tasks.length?'No matching tasks':'No tasks available'}</strong><span>{tasks.length?'Adjust the search or filters.':'Create the first client task.'}</span></div>}</section></section>;
}
function Reports({data}) {
  const year=new Date().getFullYear(),[clientId,setClientId]=useState('all'),[range,setRange]=useState('ytd'),[from,setFrom]=useState(`${year}-01-01`),[to,setTo]=useState(today());
  const dates=range==='all'?{from:'0000-01-01',to:'9999-12-31'}:range==='ytd'?{from:`${year}-01-01`,to:today()}:{from,to};
  const inRange=value=>Boolean(value)&&value.slice(0,10)>=dates.from&&value.slice(0,10)<=dates.to;
  const report=useMemo(()=>{const clientInvoices=data.invoices.filter(i=>(clientId==='all'||i.clientId===clientId)&&inRange(i.issued));const invoiceIds=new Set(clientInvoices.map(i=>i.id));const payments=data.payments.filter(p=>{const invoice=data.invoices.find(i=>i.id===p.invoiceId);return (clientId==='all'||invoice?.clientId===clientId)&&inRange(p.date)});const estimates=data.estimates.filter(e=>(clientId==='all'||e.clientId===clientId)&&inRange(e.createdAt||e.validUntil));return {invoices:clientInvoices,payments,estimates,invoiced:clientInvoices.reduce((sum,i)=>sum+Number(i.amount),0),collected:payments.reduce((sum,p)=>sum+Number(p.amount),0),outstanding:clientInvoices.reduce((sum,i)=>sum+Number(i.balance),0),estimated:estimates.reduce((sum,e)=>sum+Number(e.amount),0),invoiceIds}},[data,clientId,dates.from,dates.to]);
  const clientName=id=>data.clients.find(c=>c.id===id)?.name||'Unknown client';
  return <section className="reports-page"><div className="panel report-controls"><div><small>Report scope</small><h2>Financial activity</h2><p>Filter invoice, payment, and estimate activity by client and reporting period.</p></div><div className="report-filters"><label>Client<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="all">All clients</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Period<select value={range} onChange={e=>setRange(e.target.value)}><option value="ytd">Year to date</option><option value="all">All time</option><option value="custom">Custom range</option></select></label>{range==='custom'&&<><label>From<input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label></>}</div></div><div className="report-period"><span>{clientId==='all'?'All clients':clientName(clientId)}</span><strong>{range==='all'?'All activity':`${dates.from} — ${dates.to}`}</strong></div><section className="stats report-stats"><Stat label="Invoiced" value={money(report.invoiced)} note={`${report.invoices.length} invoices`} tone="sage"/><Stat label="Collected" value={money(report.collected)} note={`${report.payments.length} payments`} tone="ink"/><Stat label="Outstanding" value={money(report.outstanding)} note="Current balance" tone="clay"/><Stat label="Estimated" value={money(report.estimated)} note={`${report.estimates.length} estimates`} tone="blue"/></section><section className="report-grid"><ReportTable title="Invoices" empty="No invoices in this period." headings={['Invoice','Client','Issued','Amount','Balance']} rows={report.invoices.map(i=>[i.id,clientName(i.clientId),i.issued,money(i.amount),money(i.balance)])}/><ReportTable title="Payments" empty="No payments in this period." headings={['Payment','Invoice','Date','Method','Amount']} rows={report.payments.map(p=>[p.id,p.invoiceId,p.date,p.method.replace('_',' '),money(p.amount)])}/><ReportTable title="Estimates" empty="No estimates in this period." headings={['Estimate','Client','Date','Status','Amount']} rows={report.estimates.map(e=>[e.id,clientName(e.clientId),(e.createdAt||e.validUntil).slice(0,10),e.status,money(e.amount)])}/></section></section>;
}
const ReportTable=({title,empty,headings,rows})=><article className="panel report-table"><div className="panel-head"><div><small>Report detail</small><h3>{title}</h3></div><span>{rows.length} records</span></div>{rows.length?<div className="report-rows"><div className="report-row report-head">{headings.map(h=><span key={h}>{h}</span>)}</div>{rows.map((row,index)=><div className="report-row" key={`${row[0]}-${index}`}>{row.map((value,i)=><span key={i}>{value}</span>)}</div>)}</div>:<p className="nothing">{empty}</p>}</article>;
function Settings({theme,setTheme,data,reload}) {
  const [error,setError]=useState('');
  const logout=async()=>{const r=await fetch('/api/logout');const {logoutUrl}=await r.json();if(logoutUrl)location.assign(logoutUrl);else location.reload()};
  const addField=async e=>{e.preventDefault();const form=e.currentTarget;setError('');const body=Object.fromEntries(new FormData(form));const r=await fetch('/api/settings/custom-fields',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)return setError(result.error);form.reset();await reload()};
  const removeField=async id=>{setError('');const r=await fetch(`/api/settings/custom-fields/${id}`,{method:'DELETE'});if(r.ok)reload();else setError((await r.json()).error)};
  const customFields=data.settings?.customFields||[];
  return <section className="settings-grid"><article className="panel setting"><small>Appearance</small><h2>Choose your workspace light.</h2><p>The preference is stored on this device.</p><div className="theme-choices"><button className={theme==='light'?'selected':''} onClick={()=>setTheme('light')}>☀ Light</button><button className={theme==='dark'?'selected':''} onClick={()=>setTheme('dark')}>◐ Dark</button></div></article><article className="panel setting"><small>Security</small><h2>Zero Trust session</h2><p>Signed in as <strong>{data.user.email}</strong>. Logging out ends the Cloudflare Access session.</p><button className="danger" onClick={logout}>Log out</button></article><article className="panel setting custom-field-setting"><small>Workspace fields</small><h2>Custom field categories</h2><p>Add extra information to clients, invoices, or estimates. New fields appear alongside the standard fields on every matching form.</p><form className="custom-field-form" onSubmit={addField}><label>Category<select name="appliesTo" required><option value="client">Clients</option><option value="invoice">Invoices</option><option value="estimate">Estimates</option></select></label><label>Field name<input name="label" required maxLength="60" placeholder="e.g. Purchase order"/></label><button className="primary">Add field</button></form>{error&&<p className="form-error">{error}</p>}<div className="field-list">{customFields.length?customFields.map(field=><div className="field-item" key={field.id}><span><strong>{field.label}</strong><small>{field.appliesTo}s</small></span><button type="button" aria-label={`Remove ${field.label}`} onClick={()=>removeField(field.id)}>Remove</button></div>):<p className="nothing">No custom fields yet.</p>}</div></article></section>;
}

function ClientScreen({client,data,close,openInvoice}) {
  const invoices=data.invoices.filter(invoice=>invoice.clientId===client.id), invoiceIds=new Set(invoices.map(invoice=>invoice.id));
  const estimates=data.estimates.filter(estimate=>estimate.clientId===client.id), payments=data.payments.filter(payment=>invoiceIds.has(payment.invoiceId));
  const invoiced=invoices.reduce((sum,invoice)=>sum+invoice.amount,0), paid=payments.reduce((sum,payment)=>sum+payment.amount,0), due=invoices.reduce((sum,invoice)=>sum+invoice.balance,0), quoted=estimates.reduce((sum,estimate)=>sum+estimate.amount,0);
  return <div className="client-screen"><div className="client-screen-bar"><div><small>Client record</small><strong>{client.name}</strong></div><button className="quiet" onClick={close}>Close</button></div><div className="client-record"><section className="client-record-hero"><div className="client-record-avatar">{client.name[0]}</div><div><small>Client</small><h1>{client.name}</h1><p>{client.city}, {client.state} {client.zip}</p>{client.hourlyRate>0&&<span>{money(client.hourlyRate)} per hour</span>}<CustomValues data={data} type="client" record={client}/></div></section>
    <section className="client-record-stats"><div><small>Invoiced</small><strong>{money(invoiced)}</strong><span>{invoices.length} invoices</span></div><div><small>Paid</small><strong>{money(paid)}</strong><span>{payments.length} payments</span></div><div><small>Outstanding</small><strong>{money(due)}</strong><span>{invoices.filter(invoice=>invoice.balance>0).length} open</span></div><div><small>Quoted</small><strong>{money(quoted)}</strong><span>{estimates.length} estimates</span></div></section>
    <section className="client-record-grid"><article className="client-record-panel client-record-wide"><div className="client-record-heading"><div><small>Billing history</small><h2>Invoices</h2></div><span>{invoices.length} records</span></div>{invoices.length?<div className="client-detail-table"><div className="client-detail-row detail-head"><span>Invoice</span><span>Issued</span><span>Status</span><span>Total</span><span>Balance</span></div>{invoices.map(invoice=><button type="button" className="client-detail-row" key={invoice.id} onClick={()=>openInvoice(invoice)}><strong>{invoice.id}</strong><span>{invoice.issued}</span><em className={`status ${invoice.status}`}>{invoice.status}</em><span>{money(invoice.amount)}</span><span>{money(invoice.balance)} →</span></button>)}</div>:<p className="nothing">No invoices for this client.</p>}</article>
      <article className="client-record-panel"><div className="client-record-heading"><div><small>Proposals</small><h2>Quotes & estimates</h2></div><span>{estimates.length}</span></div>{estimates.length?<div className="client-record-feed">{estimates.map(estimate=><div key={estimate.id}><span><strong>{estimate.id}</strong><small>{estimate.quote}</small></span><span><em className={`status ${estimate.status}`}>{estimate.status}</em><strong>{money(estimate.amount)}</strong></span></div>)}</div>:<p className="nothing">No quotes or estimates.</p>}</article>
      <article className="client-record-panel"><div className="client-record-heading"><div><small>Receipts</small><h2>Payments</h2></div><span>{payments.length}</span></div>{payments.length?<div className="client-record-feed">{payments.map(payment=><div key={payment.id}><span><strong>{payment.id}</strong><small>{payment.date} · {payment.method.replace('_',' ')}</small></span><span><small>{payment.invoiceId}</small><strong>{money(payment.amount)}</strong></span></div>)}</div>:<p className="nothing">No payments received.</p>}</article>
    </section></div></div>;
}

function InvoiceScreen({mode,invoice,data,refresh,close,reload,recordPayment}) {
  const creating=mode==='create', client=data.clients.find(client=>client.id===invoice?.clientId);
  const [items,setItems]=useState(()=>invoice?.items||[{description:'',quantity:1,rate:''}]),[editing,setEditing]=useState(creating),[showCatalogForm,setShowCatalogForm]=useState(false),[catalogDraft,setCatalogDraft]=useState({name:'',description:'',price:'',category:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const total=items.reduce((sum,item)=>sum+(Number(item.quantity)||0)*(Number(item.rate)||0),0);
  const changeItem=(index,key,value)=>setItems(current=>current.map((item,i)=>i===index?{...item,[key]:value}:item));
  const chooseCatalogItem=(index,value)=>{if(value==='custom')return changeItem(index,'catalogId','');const catalog=(data.items||[]).find(item=>item.id===value);if(catalog)setItems(current=>current.map((item,i)=>i===index?{...item,catalogId:value,description:catalog.description||catalog.name,rate:catalog.price}:item))};
  const createCatalogItem=async()=>{setBusy(true);setError('');try{await apiJson('/api/items',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...catalogDraft,stock:0,tax1:0,tax2:0,status:'active'})});setCatalogDraft({name:'',description:'',price:'',category:''});setShowCatalogForm(false);await refresh()}catch(catalogError){setError(catalogError.message)}finally{setBusy(false)}};
  const save=async event=>{event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;const body=Object.fromEntries(new FormData(form));body.items=items;body.customFields=Object.fromEntries(Object.entries(body).filter(([key])=>key.startsWith('custom__')).map(([key,value])=>[key.slice(8),value]));Object.keys(body).filter(key=>key.startsWith('custom__')).forEach(key=>delete body[key]);try{await apiJson(creating?'/api/invoices':`/api/invoices/${encodeURIComponent(invoice.id)}/items`,{method:creating?'POST':'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});await reload()}catch(saveError){setError(saveError.message);setBusy(false)}};
  const updateStatus=async status=>{setBusy(true);setError('');try{await apiJson(`/api/invoices/${encodeURIComponent(invoice.id)}/status`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status})});await reload()}catch(statusError){setError(statusError.message);setBusy(false)}};
  const invoiceTotal=editing?total:invoice.amount, paid=creating?0:invoice.paid, balance=creating?total:Math.max(0,invoiceTotal-paid), payments=creating?[]:data.payments.filter(payment=>payment.invoiceId===invoice.id);
  return <div className="invoice-screen software-invoice-screen"><div className="invoice-screen-bar no-print"><div className="software-invoice-title"><span>▤</span><strong>Invoice <b>#{creating?'New':invoice.id}</b></strong></div><div className="invoice-screen-actions">{!creating&&!editing&&<button className="quiet" onClick={()=>setEditing(true)}>Edit items</button>}{!creating&&!editing&&invoice.balance>0&&<button className="quiet" onClick={()=>recordPayment(invoice.id)}>Record payment</button>}{!creating&&!editing&&<button className="primary" onClick={()=>window.print()}>Export PDF</button>}<button className="quiet" onClick={close}>‹ Back</button>{editing&&<button className="primary" type="submit" form="invoice-work-form" disabled={busy||!data.clients.length}>{busy?'Saving…':creating?'Save invoice':'Save changes'}</button>}</div></div>
    <div className="invoice-breadcrumb no-print"><span>Home</span><i>/</i><span>Invoices</span><i>/</i><strong>{creating?'New':invoice.id}</strong></div>
    <form id="invoice-work-form" className="invoice-software-form" onSubmit={save}><div className="invoice-work-main"><section className="software-edit-panel invoice-summary-panel"><div><label>Summary<input name="summary" defaultValue={invoice?.description||''} readOnly={!creating} placeholder="Invoice summary"/></label></div><div><label>Purchase order number<input name="purchaseOrder" readOnly={!creating} placeholder="Optional"/></label></div></section>
      <section className="invoice-address-grid"><article className="software-edit-panel"><h3>From</h3><div className="invoice-address"><strong>Kindred Innovia</strong><span>Thoughtful systems · clear work</span><span>Secure invoicing workspace</span></div></article><article className="software-edit-panel"><h3>Bill To</h3>{creating?<ClientSelect clients={data.clients}/>:<div className="invoice-address"><strong className="client-link">{client?.name}</strong><span>{client?.city}, {client?.state} {client?.zip}</span></div>}</article></section>
      <section className="software-edit-panel software-line-panel"><div className="software-panel-title"><h3>Items</h3>{editing&&<div className="line-panel-actions no-print"><button type="button" className="quiet" onClick={()=>setShowCatalogForm(value=>!value)}>Create catalog item</button><button type="button" className="primary" onClick={()=>setItems(current=>[...current,{description:'',quantity:1,rate:'',catalogId:''}])}>＋ Add item</button></div>}</div>{editing&&showCatalogForm&&<div className="inline-catalog-form no-print"><input value={catalogDraft.name} onChange={event=>setCatalogDraft({...catalogDraft,name:event.target.value})} placeholder="Item name"/><input value={catalogDraft.description} onChange={event=>setCatalogDraft({...catalogDraft,description:event.target.value})} placeholder="Description"/><input value={catalogDraft.category} onChange={event=>setCatalogDraft({...catalogDraft,category:event.target.value})} placeholder="Category"/><input value={catalogDraft.price} onChange={event=>setCatalogDraft({...catalogDraft,price:event.target.value})} type="number" min="0" step="0.01" placeholder="Price"/><button type="button" className="primary" disabled={busy||!catalogDraft.name||catalogDraft.price===''} onClick={createCatalogItem}>Save to items</button></div>}<div className="invoice-items"><div className="invoice-item invoice-item-head"><span>Product / Description</span><span>Qty</span><span>Price</span><span>Total</span><span></span></div>{items.map((item,index)=><div className="invoice-item" key={item.id||index}>{editing?<><div className="invoice-product-editor"><select value={item.catalogId||'custom'} onChange={event=>chooseCatalogItem(index,event.target.value)}><option value="custom">One-time custom item</option>{(data.items||[]).filter(catalog=>catalog.status==='active').map(catalog=><option key={catalog.id} value={catalog.id}>{catalog.name} · {money(catalog.price)}</option>)}</select><textarea value={item.description} onChange={event=>changeItem(index,'description',event.target.value)} required placeholder="Description"/></div><input value={item.quantity} onChange={event=>changeItem(index,'quantity',event.target.value)} type="number" min="0.01" step="0.01" required placeholder="Quantity"/><input value={item.rate} onChange={event=>changeItem(index,'rate',event.target.value)} type="number" min="0" step="0.01" required placeholder="Price"/></>:<><span>{item.description}</span><span>{item.quantity}</span><span>{money(item.rate)}</span></>}<strong>{money((Number(item.quantity)||0)*(Number(item.rate)||0))}</strong>{editing?<button type="button" disabled={items.length===1} onClick={()=>setItems(current=>current.filter((_,i)=>i!==index))}>×</button>:<span/>}</div>)}</div></section>
      <section className="software-edit-panel invoice-terms"><h3>Payment Terms</h3><p>Net terms · Payment is due by the date shown on this invoice.</p></section>
      <section className="software-edit-panel invoice-detail-tabs"><div className="detail-tab-row"><strong>Additional</strong><span>Notes</span><span>Payments</span></div>{creating?<CustomInputs data={data} type="invoice"/>:<><CustomValues data={data} type="invoice" record={invoice}/><div className="invoice-payments"><h3>Payment history</h3>{payments.length?payments.map(payment=><div key={payment.id}><span>{payment.date} · {payment.method.replace('_',' ')}</span><strong>{money(payment.amount)}</strong></div>):<p>No payments recorded.</p>}</div></>}</section>{error&&<p className="form-error no-print">{error}</p>}</div>
      <aside className="invoice-work-sidebar"><section className="software-edit-panel invoice-side-totals"><div><span>Subtotal</span><strong>{money(invoiceTotal)}</strong></div><div><span>Tax</span><strong>{money(0)}</strong></div><div><span>Total</span><strong>{money(invoiceTotal)}</strong></div><div><span>Paid</span><strong>{money(paid)}</strong></div><div><span>Balance</span><strong>{money(balance)}</strong></div></section><section className="software-edit-panel invoice-options"><h3>Options</h3><label>Invoice #<input value={creating?'Assigned when saved':invoice.id} readOnly/></label>{creating?<><label>Date<input name="issued" type="date" defaultValue={today()} required/></label><label>Due date<input name="due" type="date" defaultValue={addDays(14)} required/></label></>:<><label>Date<input value={invoice.issued} readOnly/></label><label>Due date<input value={invoice.due} readOnly/></label></>}<label>Currency<select disabled><option>US Dollar</option></select></label><label>Status{creating?<select disabled><option>Sent</option></select>:<select value={invoice.status} onChange={event=>updateStatus(event.target.value)} disabled={busy}><option value="draft">Draft</option><option value="sent">Sent</option><option value="paid">Paid</option><option value="overdue">Overdue</option><option value="void">Void</option></select>}</label></section></aside></form></div>;
}

function Modal({config,data,close,saved}) {
  const type=config.type,[busy,setBusy]=useState(false),[error,setError]=useState('');
  const submit=async e=>{e.preventDefault();setBusy(true);setError('');const body=Object.fromEntries(new FormData(e.currentTarget));body.customFields=Object.fromEntries(Object.entries(body).filter(([key])=>key.startsWith('custom__')).map(([key,value])=>[key.slice(8),value]));Object.keys(body).filter(key=>key.startsWith('custom__')).forEach(key=>delete body[key]);const r=await fetch(`/api/${type==='client'?'clients':`${type}s`}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await r.json();setBusy(false);if(r.ok)saved();else setError(result.error)};
  const openInvoices=data.invoices.filter(i=>i.balance>0), defaultInvoice=config.invoiceId||openInvoices[0]?.id;
  return <div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal" onSubmit={submit}><div className="modal-head"><div><small>New record</small><h2>{({client:'Add a client',invoice:'Create an invoice',estimate:'Write an estimate',item:'Add an item',subscription:'Add a subscription',payment:'Record a payment',expense:'Add an expense',task:'Add a task'})[type]}</h2></div><button type="button" onClick={close}>×</button></div>
    {type==='client'&&<><label>Name<input name="name" required placeholder="Business or client name"/></label><div className="two"><label>City<input name="city" required/></label><label>State<input name="state" required maxLength="2" placeholder="NY"/></label></div><div className="two"><label>ZIP code<input name="zip" required/></label><label>Hourly rate <small>Optional</small><input name="hourlyRate" type="number" min="0" step="0.01" placeholder="0.00"/></label></div></>}
    {type==='estimate'&&<><ClientSelect clients={data.clients}/><label>Quote<textarea name="quote" required placeholder="Describe the proposed work and terms"/></label><div className="two"><label>Valid until<input name="validUntil" type="date" defaultValue={addDays(30)} required/></label><label>Quoted amount<input name="amount" type="number" min="0.01" step="0.01" required/></label></div></>}
    {type==='item'&&<><label>Item name<input name="name" required maxLength="120" placeholder="Product or service name"/></label><div className="two"><label>Company<input name="company" placeholder="Optional"/></label><label>Category<input name="category" placeholder="e.g. Consulting"/></label></div><label>Description<textarea name="description" placeholder="Describe this product or service"/></label><div className="two"><label>In stock<input name="stock" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Price<input name="price" type="number" min="0" step="0.01" required/></label></div><div className="two"><label>Tax 1 %<input name="tax1" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Tax 2 %<input name="tax2" type="number" min="0" step="0.01" defaultValue="0"/></label></div><label>Status<select name="status" defaultValue="active"><option value="active">Active</option><option value="inactive">Inactive</option></select></label></>}
    {type==='subscription'&&<><ClientSelect clients={data.clients}/><label>Summary<input name="summary" required maxLength="200" placeholder="e.g. Monthly IT services"/></label><div className="two"><label>Next billing date<input name="nextDate" type="date" defaultValue={today()} required/></label><label>Stop date <small>Optional</small><input name="stopDate" type="date"/></label></div><div className="two"><label>Repeat every<input name="intervalCount" type="number" min="1" step="1" defaultValue="1" required/></label><label>Interval<select name="intervalUnit" defaultValue="months"><option value="days">Days</option><option value="weeks">Weeks</option><option value="months">Months</option><option value="years">Years</option></select></label></div><div className="two"><label>Recurring amount<input name="amount" type="number" min="0" step="0.01" required/></label><label>Status<select name="status" defaultValue="active"><option value="active">Active</option><option value="paused">Paused</option><option value="ended">Ended</option></select></label></div></>}
    {type==='expense'&&<><div className="two"><label>Vendor<input name="vendor" required placeholder="Vendor name"/></label><label>Date<input name="date" type="date" defaultValue={today()} required/></label></div><div className="two"><label>Client <small>Optional</small><select name="clientId" defaultValue=""><option value="">No client</option>{data.clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label>Company<input name="company" placeholder="Optional company"/></label></div><div className="two"><label>Category<input name="category" placeholder="e.g. IT Business"/></label><label>Status<select name="status" defaultValue="unbilled"><option value="unbilled">Unbilled</option><option value="billed">Billed</option><option value="reimbursed">Reimbursed</option></select></label></div><label>Description<textarea name="description" required placeholder="Describe the business expense"/></label><div className="two"><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Tax<input name="tax" type="number" min="0" step="0.01" defaultValue="0"/></label></div></>}
    {type==='task'&&<><label>Title<input name="title" required maxLength="160" placeholder="Task title"/></label><label>Description<textarea name="description" placeholder="Describe the work to complete"/></label><div className="two"><label>Client <small>Optional</small><select name="clientId" defaultValue=""><option value="">No client</option>{data.clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label>Due date<input name="dueDate" type="date" defaultValue={today()} required/></label></div><label>Status<select name="status" defaultValue="open"><option value="open">Open</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><p className="form-note">The task will be assigned to your verified Zero Trust identity.</p></>}
    {type!=='payment'&&<CustomInputs data={data} type={type}/>}
    {type==='payment'&&<><label>Invoice<select name="invoiceId" defaultValue={defaultInvoice} required>{openInvoices.map(i=><option key={i.id} value={i.id}>{i.id} · {money(i.balance)} due</option>)}</select></label><div className="two"><label>Date<input name="date" type="date" defaultValue={today()} required/></label><label>Method<select name="method"><option value="cash">Cash</option><option value="check">Check</option><option value="credit_card">Credit card</option></select></label></div><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required/></label><p className="form-note">Records the payment only. No card data is collected or processed.</p></>}
    {error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="quiet" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save record'}</button></div></form></div>;
}
const ClientSelect=({clients})=><label>Client<select name="clientId" required><option value="">Select a client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>;
const CustomInputs=({data,type})=>{const fields=fieldsFor(data,type);return fields.length?<fieldset className="custom-inputs"><legend>Custom fields</legend>{fields.map(field=><label key={field.id}>{field.label}<input name={`custom__${field.id}`} autoComplete="off"/></label>)}</fieldset>:null};
const root=globalThis.__kindredInvoiceRoot||(globalThis.__kindredInvoiceRoot=createRoot(document.getElementById('root')));
root.render(<App/>);
