import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './features.css';
import './kindred-theme.css';

const money = n => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(n || 0));
const localDate = date => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const today = () => localDate(new Date());
const addDays = days => { const d = new Date(); d.setDate(d.getDate() + days); return localDate(d); };
const menuItems = ['Overview','Invoices','Clients','Estimates','Payments','Reports','Settings'];
const MenuIcon=({name})=>{const paths={Overview:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,Invoices:<><path d="M6 2h9l5 5v15H6z"/><path d="M14 2v6h6M9 13h8M9 17h6"/></>,Clients:<><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 1 3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,Estimates:<><rect x="5" y="4" width="14" height="18" rx="2"/><path d="M9 2h6v4H9zM9 11h6M9 15h6M9 19h4"/></>,Payments:<><rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20M6 15h4"/></>,Reports:<><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/><path d="m4 7 6-5 6 7 5-4"/></>,Settings:<><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V21h-4v-.08A1.7 1.7 0 0 0 9 19.37a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.63 15 1.7 1.7 0 0 0 3.08 14H3v-4h.08A1.7 1.7 0 0 0 4.63 9a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.63 1.7 1.7 0 0 0 10 3.08V3h4v.08A1.7 1.7 0 0 0 15 4.63a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.37 9 1.7 1.7 0 0 0 20.92 10H21v4h-.08A1.7 1.7 0 0 0 19.4 15z"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">{paths[name]}</svg>};
const apiJson=async(input,options)=>{const response=await fetch(input,{...options,headers:{accept:'application/json',...(options?.headers||{})}});const contentType=response.headers.get('content-type')||'';if(!contentType.includes('application/json')){throw new Error(response.redirected?'Your Zero Trust session needs to be refreshed. Sign in again, then retry.':'The invoice API is unavailable. The page server responded instead; retry after the API starts.')}const result=await response.json();if(!response.ok)throw new Error(result.error||`Request failed (${response.status})`);return result};

function App() {
  const [data,setData]=useState(null), [page,setPage]=useState('Overview'), [modal,setModal]=useState(null);
  const [collapsed,setCollapsed]=useState(()=>localStorage.getItem('nav-collapsed')==='true');
  const [theme,setTheme]=useState(()=>localStorage.getItem('theme')||'light');
  const load=()=>apiJson('/api/workspace').then(setData);
  useEffect(()=>{load().catch(e=>setData({error:e.message}))},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('theme',theme)},[theme]);
  const toggleNav=()=>setCollapsed(v=>{localStorage.setItem('nav-collapsed',String(!v));return !v});
  const createForPage=()=>setModal(page==='Clients'?'client':page==='Estimates'?'estimate':page==='Payments'?'payment':'invoice');
  if(!data)return <div className="loading"><span>Kindred</span><p>Preparing your workspace…</p></div>;
  if(data.error)return <div className="auth-error"><p>Protected workspace</p><h1>We could not open your workspace.</h1><span>{data.error}</span><button className="retry" onClick={()=>{setData(null);load().catch(e=>setData({error:e.message}))}}>Retry connection</button></div>;
  return <div className={`shell ${collapsed?'collapsed':''}`}>
    <aside><div className="brand"><div className="mark">ki</div><div className="brand-copy"><strong>Kindred</strong><span>Invoice care</span></div><button className="collapse" onClick={toggleNav} aria-label={collapsed?'Expand menu':'Collapse menu'} title={collapsed?'Expand menu':'Collapse menu'}>{collapsed?'›':'‹'}</button></div>
      <nav>{menuItems.map(item=><button key={item} title={item} aria-label={item} className={page===item?'active':''} onClick={()=>setPage(item)}><i><MenuIcon name={item}/></i><span>{item}</span></button>)}</nav>
      <div className="aside-note"><small>Careful systems</small><p>Your financial work, held clearly and securely.</p><span>Protected by Zero Trust</span></div>
      <div className="user"><div>{data.user.email[0].toUpperCase()}</div><span><strong>{data.user.name}</strong><small>{data.user.email}</small></span></div>
    </aside>
    <main><header><div><small>Financial workspace</small><h1>{page}</h1></div><div className="header-actions">{!['Overview','Reports','Settings'].includes(page)&&<button className="primary" onClick={createForPage}>＋ New {page.slice(0,-1).toLowerCase()}</button>}</div></header>
      {page==='Overview'?<Dashboard data={data} go={setPage}/>:page==='Clients'?<Clients data={data}/>:page==='Invoices'?<Invoices data={data} pay={i=>setModal({type:'payment',invoiceId:i.id})}/>:page==='Estimates'?<Estimates data={data} reload={load}/>:page==='Payments'?<Payments data={data}/>:page==='Reports'?<Reports data={data}/>:<Settings theme={theme} setTheme={setTheme} data={data} reload={load}/>} </main>
    {modal&&<Modal config={typeof modal==='string'?{type:modal}:modal} data={data} close={()=>setModal(null)} saved={()=>{setModal(null);load()}}/>}
  </div>;
}

const Empty=({title,text,action})=><div className="empty"><span>◇</span><small>Ready when you are</small><h2>{title}</h2><p>{text}</p>{action}</div>;
function Dashboard({data,go}) {
  const total=data.invoices.reduce((s,i)=>s+i.amount,0), collected=data.payments.reduce((s,p)=>s+p.amount,0), due=data.invoices.reduce((s,i)=>s+i.balance,0);
  const percent=total?Math.round(collected/total*100):0;
  return <>{!data.clients.length&&<div className="welcome"><small>Start here</small><h2>Build a clear financial rhythm.</h2><p>Add your first client, then create an estimate or invoice. Nothing here is sample data—this workspace is entirely yours.</p><button className="primary" onClick={()=>go('Clients')}>Add your first client</button></div>}
    <section className="intro"><div><p>{new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</p><h2>A clear view of what’s moving.</h2><span>Your invoices, estimates, and payments in one calm place.</span></div><div className="orb"><span>{percent}%</span><small>collected</small></div></section>
    <section className="stats"><Stat label="Payments due" value={money(due)} note={`${data.invoices.filter(i=>i.balance>0).length} open invoices`} tone="sage"/><Stat label="Payments made" value={money(collected)} note={`${data.payments.length} recorded payments`} tone="ink"/><Stat label="Estimates open" value={data.estimates.filter(e=>e.status!=='converted').length} note={`${money(data.estimates.filter(e=>e.status!=='converted').reduce((s,e)=>s+e.amount,0))} quoted`} tone="clay"/></section>
    <section className="panel recent"><div className="panel-head"><div><small>Recent work</small><h3>Latest invoices</h3></div><button className="text-btn" onClick={()=>go('Invoices')}>View all →</button></div>{data.invoices.length?<InvoiceTable data={data}/>:<p className="nothing">No invoices yet.</p>}</section></>;
}
const Stat=({label,value,note,tone})=><div className={`stat ${tone}`}><small>{label}</small><strong>{value}</strong><span>{note}</span></div>;
const fieldsFor=(data,type)=>data.settings?.customFields?.filter(field=>field.appliesTo===type)||[];
const CustomValues=({data,type,record})=>{const values=fieldsFor(data,type).filter(field=>record.customFields?.[field.id]);return values.length?<div className="custom-values">{values.map(field=><span key={field.id}><small>{field.label}</small>{record.customFields[field.id]}</span>)}</div>:null};
function InvoiceTable({data,pay}) { return <div className="table"><div className="tr th invoice-row"><span>Invoice</span><span>Client</span><span>Due</span><span>Status</span><span>Balance</span><span></span></div>{data.invoices.map(i=><div className="tr invoice-row" key={i.id}><span><strong>{i.id}</strong><small>{i.description}</small><CustomValues data={data} type="invoice" record={i}/></span><span>{data.clients.find(c=>c.id===i.clientId)?.name}</span><span>{i.due}</span><span><em className={`status ${i.status}`}>{i.status}</em></span><span><strong>{money(i.balance)}</strong><small>{money(i.paid)} paid</small></span><span>{i.balance>0&&pay?<button className="mini" onClick={()=>pay(i)}>Record payment</button>:null}</span></div>)}</div> }
function Invoices({data,pay}) { return data.invoices.length?<section className="panel page-panel"><InvoiceTable data={data} pay={pay}/></section>:<Empty title="No invoices yet" text="Create an invoice directly, or convert an approved estimate into one."/>; }
function Clients({data}) { return data.clients.length?<section className="cards">{data.clients.map(c=>{const inv=data.invoices.filter(i=>i.clientId===c.id), pays=data.payments.filter(p=>inv.some(i=>i.id===p.invoiceId));return <article className="client" key={c.id}><div className="client-top"><div>{c.name[0]}</div><em>Active</em></div><h3>{c.name}</h3><p>{c.city}, {c.state} {c.zip}</p><span>{money(c.hourlyRate)} / hour</span><CustomValues data={data} type="client" record={c}/><div className="client-metrics"><b>{inv.length}<small>Invoices</small></b><b>{money(pays.reduce((s,p)=>s+p.amount,0))}<small>Paid</small></b><b>{money(inv.reduce((s,i)=>s+i.balance,0))}<small>Due</small></b></div><footer><small>Associated records</small><strong>{inv.map(i=>i.id).join(', ')||'None yet'}</strong></footer></article>})}</section>:<Empty title="No clients yet" text="Clients include their service location, hourly rate, invoices, estimates, payments made, and balance due."/>; }
function Estimates({data,reload}) { const convert=async id=>{const r=await fetch(`/api/estimates/${id}/convert`,{method:'POST'});if(r.ok)reload()};return data.estimates.length?<section className="panel page-panel"><div className="table"><div className="tr th estimate-row"><span>Estimate</span><span>Client</span><span>Quote</span><span>Valid until</span><span>Amount</span><span></span></div>{data.estimates.map(e=><div className="tr estimate-row" key={e.id}><span><strong>{e.id}</strong><small>{e.status}</small></span><span>{data.clients.find(c=>c.id===e.clientId)?.name}</span><span>{e.quote}<CustomValues data={data} type="estimate" record={e}/></span><span>{e.validUntil}</span><span><strong>{money(e.amount)}</strong></span><span>{e.status!=='converted'?<button className="mini" onClick={()=>convert(e.id)}>Convert to invoice</button>:<small>{e.invoiceId}</small>}</span></div>)}</div></section>:<Empty title="No estimates yet" text="Write a quote, set its value and validity date, then convert it to an invoice with one click."/>; }
function Payments({data}) { return data.payments.length?<section className="panel page-panel"><div className="table"><div className="tr th payment-row"><span>Payment</span><span>Invoice</span><span>Client</span><span>Date</span><span>Method</span><span>Amount</span></div>{data.payments.map(p=>{const i=data.invoices.find(i=>i.id===p.invoiceId);return <div className="tr payment-row" key={p.id}><span><strong>{p.id}</strong></span><span>{p.invoiceId}</span><span>{data.clients.find(c=>c.id===i?.clientId)?.name}</span><span>{p.date}</span><span className="method">{p.method.replace('_',' ')}</span><span><strong>{money(p.amount)}</strong></span></div>})}</div></section>:<Empty title="No payments recorded" text="Record cash, check, or credit card payments against an open invoice. This does not connect to an external processor."/>; }
function Reports({data}) {
  const year=new Date().getFullYear(),[clientId,setClientId]=useState('all'),[range,setRange]=useState('ytd'),[from,setFrom]=useState(`${year}-01-01`),[to,setTo]=useState(today());
  const dates=range==='all'?{from:'0000-01-01',to:'9999-12-31'}:range==='ytd'?{from:`${year}-01-01`,to:today()}:{from,to};
  const inRange=value=>Boolean(value)&&value.slice(0,10)>=dates.from&&value.slice(0,10)<=dates.to;
  const report=useMemo(()=>{const clientInvoices=data.invoices.filter(i=>(clientId==='all'||i.clientId===clientId)&&inRange(i.issued));const invoiceIds=new Set(clientInvoices.map(i=>i.id));const payments=data.payments.filter(p=>{const invoice=data.invoices.find(i=>i.id===p.invoiceId);return (clientId==='all'||invoice?.clientId===clientId)&&inRange(p.date)});const estimates=data.estimates.filter(e=>(clientId==='all'||e.clientId===clientId)&&inRange(e.createdAt||e.validUntil));return {invoices:clientInvoices,payments,estimates,invoiced:clientInvoices.reduce((sum,i)=>sum+Number(i.amount),0),collected:payments.reduce((sum,p)=>sum+Number(p.amount),0),outstanding:clientInvoices.reduce((sum,i)=>sum+Number(i.balance),0),estimated:estimates.reduce((sum,e)=>sum+Number(e.amount),0),invoiceIds}},[data,clientId,dates.from,dates.to]);
  const clientName=id=>data.clients.find(c=>c.id===id)?.name||'Unknown client';
  return <section className="reports-page"><div className="panel report-controls"><div><small>Report scope</small><h2>Financial activity</h2><p>Filter invoice, payment, and estimate activity by client and reporting period.</p></div><div className="report-filters"><label>Client<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="all">All clients</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Period<select value={range} onChange={e=>setRange(e.target.value)}><option value="ytd">Year to date</option><option value="all">All time</option><option value="custom">Custom range</option></select></label>{range==='custom'&&<><label>From<input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label></>}</div></div><div className="report-period"><span>{clientId==='all'?'All clients':clientName(clientId)}</span><strong>{range==='all'?'All activity':`${dates.from} — ${dates.to}`}</strong></div><section className="stats report-stats"><Stat label="Invoiced" value={money(report.invoiced)} note={`${report.invoices.length} invoices`} tone="sage"/><Stat label="Collected" value={money(report.collected)} note={`${report.payments.length} payments`} tone="ink"/><Stat label="Outstanding" value={money(report.outstanding)} note="Current balance" tone="clay"/><Stat label="Estimated" value={money(report.estimated)} note={`${report.estimates.length} estimates`} tone="blue"/></section><section className="report-grid"><ReportTable title="Invoices" empty="No invoices in this period." headings={['Invoice','Client','Issued','Amount','Balance']} rows={report.invoices.map(i=>[i.id,clientName(i.clientId),i.issued,money(i.amount),money(i.balance)])}/><ReportTable title="Payments" empty="No payments in this period." headings={['Payment','Invoice','Date','Method','Amount']} rows={report.payments.map(p=>[p.id,p.invoiceId,p.date,p.method.replace('_',' '),money(p.amount)])}/><ReportTable title="Estimates" empty="No estimates in this period." headings={['Estimate','Client','Date','Status','Amount']} rows={report.estimates.map(e=>[e.id,clientName(e.clientId),(e.createdAt||e.validUntil).slice(0,10),e.status,money(e.amount)])}/></section></section>;
}
const ReportTable=({title,empty,headings,rows})=><article className="panel report-table"><div className="panel-head"><div><small>Report detail</small><h3>{title}</h3></div><span>{rows.length} records</span></div>{rows.length?<div className="report-rows"><div className="report-row report-head">{headings.map(h=><span key={h}>{h}</span>)}</div>{rows.map((row,index)=><div className="report-row" key={`${row[0]}-${index}`}>{row.map((value,i)=><span key={i}>{value}</span>)}</div>)}</div>:<p className="nothing">{empty}</p>}</article>;
function Settings({theme,setTheme,data,reload}) {
  const [error,setError]=useState('');
  const logout=async()=>{const r=await fetch('/api/logout');const {logoutUrl}=await r.json();if(logoutUrl)location.assign(logoutUrl);else location.reload()};
  const addField=async e=>{e.preventDefault();const form=e.currentTarget;setError('');const body=Object.fromEntries(new FormData(form));const r=await fetch('/api/settings/custom-fields',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)return setError(result.error);form.reset();await reload()};
  const removeField=async id=>{setError('');const r=await fetch(`/api/settings/custom-fields/${id}`,{method:'DELETE'});if(r.ok)reload();else setError((await r.json()).error)};
  const customFields=data.settings?.customFields||[];
  return <section className="settings-grid"><article className="panel setting"><small>Appearance</small><h2>Choose your workspace light.</h2><p>The preference is stored on this device.</p><div className="theme-choices"><button className={theme==='light'?'selected':''} onClick={()=>setTheme('light')}>☀ Light</button><button className={theme==='dark'?'selected':''} onClick={()=>setTheme('dark')}>◐ Dark</button></div></article><article className="panel setting"><small>Security</small><h2>Zero Trust session</h2><p>Signed in as <strong>{data.user.email}</strong>. Logging out ends the Cloudflare Access session.</p><button className="danger" onClick={logout}>Log out</button></article><article className="panel setting custom-field-setting"><small>Workspace fields</small><h2>Custom field categories</h2><p>Add extra information to clients, invoices, or estimates. New fields appear alongside the standard fields on every matching form.</p><form className="custom-field-form" onSubmit={addField}><label>Category<select name="appliesTo" required><option value="client">Clients</option><option value="invoice">Invoices</option><option value="estimate">Estimates</option></select></label><label>Field name<input name="label" required maxLength="60" placeholder="e.g. Purchase order"/></label><button className="primary">Add field</button></form>{error&&<p className="form-error">{error}</p>}<div className="field-list">{customFields.length?customFields.map(field=><div className="field-item" key={field.id}><span><strong>{field.label}</strong><small>{field.appliesTo}s</small></span><button type="button" aria-label={`Remove ${field.label}`} onClick={()=>removeField(field.id)}>Remove</button></div>):<p className="nothing">No custom fields yet.</p>}</div></article></section>;
}

function Modal({config,data,close,saved}) {
  const type=config.type,[busy,setBusy]=useState(false),[error,setError]=useState('');
  const submit=async e=>{e.preventDefault();setBusy(true);setError('');const body=Object.fromEntries(new FormData(e.currentTarget));body.customFields=Object.fromEntries(Object.entries(body).filter(([key])=>key.startsWith('custom__')).map(([key,value])=>[key.slice(8),value]));Object.keys(body).filter(key=>key.startsWith('custom__')).forEach(key=>delete body[key]);const r=await fetch(`/api/${type==='client'?'clients':`${type}s`}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await r.json();setBusy(false);if(r.ok)saved();else setError(result.error)};
  const openInvoices=data.invoices.filter(i=>i.balance>0), defaultInvoice=config.invoiceId||openInvoices[0]?.id;
  return <div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal" onSubmit={submit}><div className="modal-head"><div><small>New record</small><h2>{({client:'Add a client',invoice:'Create an invoice',estimate:'Write an estimate',payment:'Record a payment'})[type]}</h2></div><button type="button" onClick={close}>×</button></div>
    {type==='client'&&<><label>Name<input name="name" required placeholder="Business or client name"/></label><div className="two"><label>City<input name="city" required/></label><label>State<input name="state" required maxLength="2" placeholder="NY"/></label></div><div className="two"><label>ZIP code<input name="zip" required/></label><label>Hourly rate<input name="hourlyRate" type="number" min="0" step="0.01" required/></label></div></>}
    {type==='invoice'&&<><ClientSelect clients={data.clients}/><div className="two"><label>Issued<input name="issued" type="date" defaultValue={today()} required/></label><label>Payment due<input name="due" type="date" defaultValue={addDays(14)} required/></label></div><label>Description<input name="description" required/></label><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required/></label></>}
    {type==='estimate'&&<><ClientSelect clients={data.clients}/><label>Quote<textarea name="quote" required placeholder="Describe the proposed work and terms"/></label><div className="two"><label>Valid until<input name="validUntil" type="date" defaultValue={addDays(30)} required/></label><label>Quoted amount<input name="amount" type="number" min="0.01" step="0.01" required/></label></div></>}
    {type!=='payment'&&<CustomInputs data={data} type={type}/>}
    {type==='payment'&&<><label>Invoice<select name="invoiceId" defaultValue={defaultInvoice} required>{openInvoices.map(i=><option key={i.id} value={i.id}>{i.id} · {money(i.balance)} due</option>)}</select></label><div className="two"><label>Date<input name="date" type="date" defaultValue={today()} required/></label><label>Method<select name="method"><option value="cash">Cash</option><option value="check">Check</option><option value="credit_card">Credit card</option></select></label></div><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required/></label><p className="form-note">Records the payment only. No card data is collected or processed.</p></>}
    {error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="quiet" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save record'}</button></div></form></div>;
}
const ClientSelect=({clients})=><label>Client<select name="clientId" required><option value="">Select a client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>;
const CustomInputs=({data,type})=>{const fields=fieldsFor(data,type);return fields.length?<fieldset className="custom-inputs"><legend>Custom fields</legend>{fields.map(field=><label key={field.id}>{field.label}<input name={`custom__${field.id}`} autoComplete="off"/></label>)}</fieldset>:null};
createRoot(document.getElementById('root')).render(<App/>);
